from astropy import units as u

example_FITS ='../data/HL_Tau_prep_for_Scopesim.fits'

file_psf_077 = '../models/img_n/Circular_Gaussian_unres_pt_source_0.77Jy.fits'
file_psf_1_2 = '../models/img_n/Circular_Gaussian_unres_pt_source_5.085Jy.fits'
file_psf_1_20 = '../models/img_n/Circular_Gaussian_unres_pt_source_0.5085Jy.fits'

file_1Jy = '../models/img_n/Circular_Gaussian_unres_pt_source_1.0Jy.fits'
file_disk_1Jy = '../models/img_n/Uniform_disk_uniform_source1.0Jy.fits'

file_circinus_1pt_2ellipt = '../models/img_n/3_Gaussians_Circinus_1pt_2elliptical.fits'
file_circinus_1pt_1ellipt = '../models/img_n/2_Gaussians_Circinus_1pt_1elliptical.fits'

file_circinus_30mas = '../models/img_n/3_Gaussians_Circinus_30mas.fits'
file_circinus_1as = '../models/img_n/3_Gaussians_Circinus_1as.fits'
file_circinus_1_20 = '../models/img_n/3_Gaussians_Circinus_1_20_flux.fits'
file_circinus_1_2 = '../models/img_n/3_Gaussians_Circinus_1_2_flux.fits'


file_real_circinus_N_band = '../models/img_n/N_band_Circinus.fits'
file_real_circinus_N_band_untouched = '../models/img_n/N_band_Circinus_untouched.fits'


# Constants
L_band = 4 *u.um 
N_band = 12 *u.um 

# Variables linked to METIS
d_METIS = 39.3 * u.m # diameter of the primary mirror in the ELT

# Variables linked to ScopeSim
screen_size = 2048 # the size of the screen returned
screen_center = 1024 # the center of the source is located at the center of the screen
METIS_N_band_pixel_scale = 6.79 *u.mas # given by the header of the image generated by ScopeSim
METIS_L_band_pixel_scale = 5.47 *u.mas 

exptime_1hour = 3600 *u.s
exptime_1second = 1 *u.s
exptime_5min = 5*60*u.s

# N-band Circinus 
D_circinus = 4.2 *u.Mpc
Total_flux_circinus = (7.79+1.61+0.77)*u.Jy

CDELT_circinus_original = 3.90625 *u.mas
pxl_polar_x = 27
pxl_polar_y = 11
pxl_disk_x = 13
pxl_disk_y = 3
pxl_unres_x = 1.5 

theta_polar = 27*u.degree
theta_disk = theta_polar + 90*u.degree

flux_unres = 0.77*u.Jy
flux_disk = 1.61 *u.Jy
flux_polar = 7.79*u.Jy

total_flux_extended_circinus = (7.79+1.61)*u.Jy
frac_flux_polar_circinus = flux_polar/total_flux_extended_circinus
frac_flux_disk_circinus = flux_disk/total_flux_extended_circinus
real_flux_ratio = flux_unres/Total_flux_circinus

#L-band Circinus 
THETA_L_circinus = 16.3*u.mas 
r_L_circinus = 0.63
flux_L_circinus = 510*u.mJy

# Conversion factor
"""Jy_to_ADU = 77539.47
Jy_to_ADU_chopnod = 305060.47"""
Jy_to_ADU = 100727.66/0.015
Jy_to_ADU_chopnod = 396031.88/(4*0.015)

dit_015 = 0.015 *u.s

# generation limit of gaussian
gen_fact = 10
