from astropy import units as u

example_FITS ='../data/HL_Tau_prep_for_Scopesim.fits'

file_psf_077 = '../outputs/img_n/unres_pt_source_0.77Jy/MODEL_Circular_Gaussian.fits'
file_circinus_3_components_N_band = '../outputs/Circinus_pt_and_extended_N-band.fits'
file_circinus_extended_only = '../outputs/Circinus_Extended_only_N-band.fits'
file_real_circinus_N_band = '../outputs/REAL_Circinus_N_band.fits'

file_real_circinus_N_band = '../outputs/REAL_Circinus_N_band.fits'
file_real_circinus_N_band_untouched = '../data/N_band_Circinus_untouched.fits'


# Constants
L_band = 4 *u.um 
N_band = 12 *u.um 

# Variables linked to METIS
d_METIS = 39.3 * u.m # diameter of the primary mirror in the ELT

# Variables linked to ScopeSim
screen_size = 2048 # the size of the screen returned
screen_center = 1024 # the center of the source is located at the center of the screen
N_band_pixel_scale = 6.79 *u.mas # given by the header of the image generated by ScopeSim
L_band_pixel_scale = 1 *u.mas #! To change, not the good value

exptime_1hour = 3600 *u.s
exptime_1second = 1 *u.s
exptime_5min = 5*60*u.s

# Circinus 
D_circinus = 4.2 *u.Mpc
Max_flux_circinus = (7.79+1.61+0.77)*u.Jy

# Conversion factor
Jy_to_ADU = 77539.47
Jy_to_ADU_chopnod = 305060.47

